language: go

go:
  - '1.5.1'

sudo: required
services:
  - docker

env:
  - GO15VENDOREXPERIMENT=1

before_install:
  - curl -L https://github.com/Masterminds/glide/releases/download/0.6.1/glide-linux-amd64.zip > glide.zip
  - unzip glide.zip
  - export PATH="$PATH:$PWD/linux-amd64"
  - go get -u github.com/golang/lint/golint

script:
  - make
